spring.datasource.url=jdbc:mysql://localhost:3306/focusgrow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

spring.config.import=optional:classpath:local-secret.properties